name: package

on:
  workflow_call:

jobs:
  deb:
    name: package (.deb)
    runs-on: ubuntu-24.04
    env:
      GENERATOR: DEB
    steps:
      - uses: actions/checkout@v4

      - name: Install packaging tools + system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y make dpkg-dev ninja-build libgl1-mesa-dev mesa-common-dev libxrandr-dev libxi-dev libxinerama-dev libxcursor-dev libxss-dev libpulse-dev libxkbcommon-dev libwayland-dev

      - name: Install conan
        run: |
          python3 -m venv "$HOME/.conan-venv"
          "$HOME/.conan-venv/bin/pip" install --upgrade pip conan
          echo "$HOME/.conan-venv/bin" >> "$GITHUB_PATH"

      - name: Detect conan profile
        run: conan profile detect --force

      - name: Configure sudo for system reqs
        run: conan config set tools.system.package_manager:sudo=True

      - name: Conan install
        run: conan install . -of build -s build_type=Release -s compiler.cppstd=gnu20 --build=missing

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="$PWD/build/conan_toolchain.cmake"

      - name: Build
        run: cmake --build build -j 2

      - name: Package
        run: cpack -B build -G "$GENERATOR"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: grfeditor-deb
          path: build/grfeditor-*.deb
          if-no-files-found: error

  rpm:
    name: package (.rpm)
    runs-on: ubuntu-24.04
    container: fedora:41
    env:
      GENERATOR: RPM
    steps:
      - uses: actions/checkout@v4

      - name: Install packaging tools + system deps
        run: |
          dnf install -y gcc-c++ make cmake python3 python3-pip rpm-build git ninja-build \
            mesa-libEGL-devel mesa-libGL-devel libXrandr-devel libXi-devel libXinerama-devel \
            libXcursor-devel libXss-devel pulseaudio-libs-devel libxkbcommon-devel wayland-devel

      - name: Install conan
        run: |
          python3 -m venv "$HOME/.conan-venv"
          "$HOME/.conan-venv/bin/pip" install --upgrade pip conan
          echo "$HOME/.conan-venv/bin" >> "$GITHUB_PATH"

      - name: Detect conan profile
        run: conan profile detect --force

      - name: Conan install
        run: conan install . -of build -s build_type=Release -s compiler.cppstd=gnu20 --build=missing

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="$PWD/build/conan_toolchain.cmake"

      - name: Build
        run: cmake --build build -j 2

      - name: Package
        run: cpack -B build -G "$GENERATOR"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: grfeditor-rpm
          path: build/grfeditor-*.rpm
          if-no-files-found: error